// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import {
  getDatabaseUrl,
  hasDbConfig,
  resolveDbProvider,
} from "./src/helper/db-provider";

// Hybrid database (Option A): the provider is chosen per environment from
// DB_PROVIDER, or inferred from DATABASE_URL. The connection string is taken
// from DATABASE_URL if set, otherwise composed from the individual DB_*
// parameters (DB_HOST/DB_PORT/DB_USER/DB_PASSWORD/DB_NAME/DB_SSLMODE).
// The schema datasource provider must match (set it with
// `npm run db:provider:<mysql|postgres>`), and the migrations path is
// selected here so each provider keeps its own migration history:
//   - postgresql -> prisma/migrations
//   - mysql      -> prisma/migrations-mysql
const provider = resolveDbProvider(
  process.env["DATABASE_URL"],
  process.env["DB_PROVIDER"]
);

const databaseUrl = hasDbConfig()
  ? getDatabaseUrl()
  : provider === "mysql"
    ? "mysql://root@localhost:3306/mexpo"
    : "postgresql://postgres:postgres@localhost:5432/postgres";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: provider === "mysql" ? "prisma/migrations-mysql" : "prisma/migrations",
    seed: 'ts-node prisma/seed.ts',
  },
  datasource: {
    url: databaseUrl,
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
