name: Deploy Next.js

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 9002
          script: |
            cd /home/dev-backend-expo
            git pull origin main
            npm install
            npx prisma migrate deploy
            npx prisma generate
            npm run build
            pm2 restart backend-expo
            pm2 reload backend-expo
